meta:
  new_timecard_day: 2

messages:
  todays_date: "Today's date is:"
  new_timecard: "Please fill out a new card today"
  date_format: "%-m-%-d-%Y"

render:
  width: 600
  height: 800
  template: "template.html"
  out_image: "kindle-signage.png"
  temp_html:
  render_cmd: 'wkhtmltoimage --width {width} --height {height} {temp_html} {out_image}'
  optim_cmd: 'pngcrush -rem gAMA -rem cHRM -rem iCCP -rem sRGB -rem alla -rem text -c 0 -ow {out_image}'